portailva/association/urls.py
from django.conf.urls import url

from portailva.association.views import AssociationDetailView, AssociationUpdateView, AssociationListView, \
    AssociationNewView, AssociationDeleteView, AssociationMandateListView, AssociationMandateNewView, \
    AssociationMandatePeopleNewView, AssociationMandatePeopleUpdateView, AssociationMandatePeopleDeleteView, \
    AssociationRequirementListView, AssociationRequirementAchieveView, RequirementListView, RequirementDetailView, \
    GlobalDirectoryView, AssociationMandateChangePhoneVisibility, RequirementNewView, RequirementDeleteView, \
    RequirementUpdateView

urlpatterns = [
    # Association links
    url('^association/new/$', AssociationNewView.as_view(), name='association-new'),
    url('^association/(?P<pk>\d+)/$', AssociationDetailView.as_view(), name='association-detail'),
    url('^association/(?P<pk>\d+)/update/$', AssociationUpdateView.as_view(), name='association-update'),

    # Mandate
    url('^association/(?P<association_pk>\d+)/mandate/$', AssociationMandateListView.as_view(), name='association-mandate-list'),
    url('^association/(?P<association_pk>\d+)/mandate/new/$', AssociationMandateNewView.as_view(), name='association-mandate-new'),
    url('^association/(?P<association_pk>\d+)/mandate/(?P<mandate_pk>\d+)/change_phone_visibility$', AssociationMandateChangePhoneVisibility.as_view(),
        name='association-mandate-change-phone-visibiity'),
    url('^association/(?P<association_pk>\d+)/mandate/(?P<mandate_pk>\d+)/people/new/$', AssociationMandatePeopleNewView.as_view(),
        name='association-mandate-people-new'),
    url('^association/(?P<association_pk>\d+)/mandate/(?P<mandate_pk>\d+)/people/(?P<pk>\d+)/edit/$',
        AssociationMandatePeopleUpdateView.as_view(), name='association-mandate-people-update'),
    url('^association/(?P<association_pk>\d+)/mandate/(?P<mandate_pk>\d+)/people/(?P<pk>\d+)/delete/$',
        AssociationMandatePeopleDeleteView.as_view(), name='association-mandate-people-delete'),

    # Requirements
    url('^association/(?P<association_pk>\d+)/requirement/$', AssociationRequirementListView.as_view(),
        name='association-requirement-list'),
    url('^association/(?P<association_pk>\d+)/requirement/(?P<pk>\d+)/achieve/$', AssociationRequirementAchieveView.as_view(),
        name='association-requirement-achieve'),

    # Admin stuff
    url('^association/$', AssociationListView.as_view(), name='association-list'),
    url('^requirement/$', RequirementListView.as_view(), name='requirement-list'),
    url('^requirement/new/$', RequirementNewView.as_view(), name='requirement-new'),
    url('^requirement/(?P<pk>\d+)/$', RequirementDetailView.as_view(), name='requirement-detail'),
    url('^requirement/(?P<pk>\d+)/update/$', RequirementUpdateView.as_view(), name='requirement-update'),
    url('^requirement/(?P<pk>\d+)/delete/$', RequirementDeleteView.as_view(), name='requirement-delete'),
    url('^association/(?P<pk>\d+)/delete/$', AssociationDeleteView.as_view(), name='association-delete'),

    # Association Directory
    url('^associations$', GlobalDirectoryView.as_view(), name='associations-directory')

]

portailva/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from portailva.pages.views import HomeView, DashBoardView, Handler400, Handler503, Handler404, Handler403, Handler401, \
    Handler502, MentionView, SitemapView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/$', DashBoardView.as_view(), name='admin-dashboard'),

    url(r'', include('portailva.association.urls')),
    url(r'^member/', include('portailva.member.urls')),
    url(r'', include('portailva.directory.urls')),
    url(r'', include('portailva.file.urls')),
    url(r'', include('portailva.utils.urls')),
    url(r'', include('portailva.event.urls')),
    url(r'', include('portailva.newsletter.urls')),
    url(r'export/', include('portailva.export.urls')),

    # REST API
    url(r'^api/', include('portailva.api_urls')),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^mention/$', MentionView.as_view(), name='mention'),
    url('^sitemap.xml$', SitemapView.as_view(), name='public-article-sitemap'),
    url(r'^$', HomeView.as_view(), name='homepage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = Handler400.as_view() # Bad Request
handler401 = Handler401.as_view() # Unauthorized
handler403 = Handler403.as_view() # Forbidden
handler404 = Handler404.as_view() # Not Found
handler500 = 'portailva.pages.views.handler500' # Internal Server Error
handler502 = Handler502.as_view() # Bad Gateway
handler503 = Handler503.as_view() # Service Unavailable

portailva/association/models.py
import json
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User

from portailva.file.models import AssociationFile
from portailva.utils.fields import LogoURLField
from portailva.utils.models import Place
from portailva.utils.validators import validate_iban, validate_siren


class Category(models.Model):
    """
    A Category is a simple container for Associations.
    There is no kind of logic in a Category. It simply here for Association presentation in a predefined order.
    """
    name = models.CharField("Nom", max_length=50)
    position = models.IntegerField("Position")
    # max_len at 24 since you can have rgba(xxx, yyy, zzz, aaa)
    color = models.CharField("Couleur", max_length=24, default="#007bff", help_text="Used for Association display, a CSS compatible color value is expected")
    latex_color_name = models.CharField(max_length=100,
                                        help_text="Used for LaTeX generation, see the .sty for more info")

    class Meta(object):
        default_permissions = ('add', 'change', 'delete', 'admin',)

    def __str__(self):
        return self.name

    def get_directory_associations(self):
        return (self.association_set
                .filter(is_validated=True)
                .filter(directory_entries__isnull=False)
                .filter(directory_entries__is_online=True)
                .distinct()
                .order_by('name'))


class Association(models.Model):
    """
    An Association.
    """
    name = models.CharField("Nom officiel", max_length=50)
    acronym = models.CharField("Nom usuel ou acronyme", max_length=20, null=True, blank=True)
    description = models.TextField(
        "Description",
        help_text="Cette description n'est pas visible dans le Bot'INSA",
    )
    active_members_number = models.PositiveIntegerField("Nombre de membres actifs", default=0)
    all_members_number = models.PositiveIntegerField("Nombre de membres adhérents", default=0)

    is_active = models.BooleanField("Est active", default=True)
    is_validated = models.BooleanField("Est validée", default=False)
    has_place = models.BooleanField("Possède un local?", default=False)
    room = models.ForeignKey(Place, verbose_name="Local", related_name="association", blank=True, null=True,
                              on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, verbose_name="Catégorie", on_delete=models.PROTECT)
    users = models.ManyToManyField(User, verbose_name="Utilisateurs", related_name='associations', blank=True)

    commentary = models.TextField(
        "Commentaires",
        help_text="Cette description n'est pas visible pour les non-administateurs",
        blank=True
    )
    moderated_by = models.ManyToManyField(User, verbose_name="Référent CVA", related_name='referent', blank=True)

    logo_url = LogoURLField("URL du logo", blank=True)

    iban = models.CharField("IBAN", max_length=50, blank=True, validators=[validate_iban])
    bic = models.CharField("BIC", max_length=15, blank=True)
    rna = models.CharField("Numéro RNA", max_length=10, blank=True, help_text="La date extacte ainsi que les numéros d'identifications ci-dessous peuvent être facilement retrouvés en cherchant votre asso sur le site : entreprise.data.gouv.fr")
    siren = models.CharField("Numéro SIREN", max_length=9, blank=True, help_text="Format : XXXXXXXXX où X est un chiffre entre 0 et 9", validators=[validate_siren])

    created_at = models.DateTimeField("Date d'ajout", auto_now_add=True)
    updated_at = models.DateTimeField("Dernière mise à jour", auto_now=True)

    created_officially_at = models.DateField("Date de création", help_text="Format : JJ/MM/AAAA", null=True, blank=True)

    class Meta(object):
        default_permissions = ('add', 'change', 'delete', 'admin',)

    def __str__(self):
        return self.name

    def current_directory_entry(self):
        return self.directory_entries.filter(is_online=True).last()

    def online_events(self):
        return self.events.filter(is_online=True).filter(ends_at__gte=datetime.now()).order_by('begins_at')

    def can_admin(self, user):
        """
        Checks if an user can administrate an association.
        The association can be administrated if:
        - The user is an admin
        :param user: the user to check the rights
        :return: `True` if the user can access this association, `False` otherwise.
        """
        if user is not None and user.is_authenticated:
            if user.is_superuser or user.has_perm('association.admin_association'):
                return True

        return False

    def can_access(self, user):
        """
        Checks if an user can access information about an association.
        The association can be accessed if:
        - The user belongs to association users list
        - The user is an admin
        :param user: the user to check the rights
        :return: `True` if the user can access this association, `False` otherwise.
        """
        if user is not None and user.is_authenticated:
            if self.can_admin(user):
                return True
            elif user in self.users.all():
                return True

        return False


class Mandate(models.Model):
    """
    A Mandate is an Association period of activity. During a Mandate, some people manage the Association (like the
    president or the treasurer).
    """
    begins_at = models.DateField("Début du mandat")
    ends_at = models.DateField("Fin du mandat")
    share_phone = models.BooleanField("Autoriser le partage du numéro", default=False)
    created_at = models.DateTimeField("Date d'ajout", auto_now_add=True)

    association = models.ForeignKey(Association, verbose_name="Association", related_name="mandates",
                                    on_delete=models.CASCADE)

    class Meta(object):
        default_permissions = ('add', 'change', 'delete', 'admin',)

    def __str__(self):
        return "Du " + str(self.begins_at) + " au " + str(self.ends_at)

    def get_president(self):
        return self.peoples.filter(role__name__istartswith='président')

class PeopleRole(models.Model):
    """
    During a Mandate, each People has a specific PeopleRole.
    """
    name = models.CharField("Nom du poste", max_length=50)
    position = models.IntegerField("Position", blank=True, default=1)

    class Meta(object):
        default_permissions = ('add', 'change', 'delete', 'admin',)
        ordering = ('position',)

    def __str__(self):
        return self.name


class People(models.Model):
    """
    A People designates someone who manages the Association during a Mandate.
    """
    first_name = models.CharField("Prénom", max_length=50)
    last_name = models.CharField("Nom", max_length=50)
    email = models.EmailField("Adresse email", max_length=250)
    phone = models.CharField("Numéro de téléphone", max_length=50, default='')

    role = models.ForeignKey(PeopleRole, verbose_name="Rôle", related_name="peoples", on_delete=models.SET_NULL,
                             null=True)
    mandate = models.ForeignKey(Mandate, verbose_name="Mandat", related_name="peoples", on_delete=models.CASCADE)

    class Meta(object):
        default_permissions = ('add', 'change', 'delete', 'admin',)
        ordering = ('role',)

    def __str__(self):
        return self.first_name + " " + self.last_name.upper()


class RequirementManager(models.Manager):
    def get_all_active(self):
        return self.all().filter(active_until__gt=datetime.now())


class Requirement(models.Model):
    """
    A Requirement represents an action that an Association can accomplish.
    """
    REQUIREMENT_TYPES = (
        ('mandate', 'Mandat'),
        ('file', 'Fichier'),
        ('accomplishment', 'Validation manuelle'),
        ('room', 'Validation manuelle (nécessite un local)'),
        ('role', 'Mandat (vérifie la présence d\'une personne avec un rôle précis)')
    )
    name = models.CharField("Nom", max_length=100)
    type = models.CharField("Type de condition", max_length=40, choices=REQUIREMENT_TYPES)
    data = models.TextField("Meta données", blank=True, default='{}')
    help_text = models.TextField("Texte d'aide", blank=True, null=True)

    active_until = models.DateTimeField("Date de fin de validité")

    objects = RequirementManager()

    class Meta(object):
        ordering = ('name',)
        default_permissions = ('add', 'change', 'delete', 'admin',)

    def __str__(self):
        return '[' + self.type + '] ' + self.name

    def is_achieved(self, association_id):
        data = json.loads(self.data)
        achieved = False
        if self.type == 'file':
            folder_id = int(data['tag_id'])
            nb_files = AssociationFile.objects \
                .filter(association__id=association_id) \
                .filter(folder__id__exact=folder_id) \
                .count()
            if nb_files > 0:
                achieved = True

        if self.type == 'mandate':
            year = data['year']
            try:
                last_mandate = Mandate.objects \
                                   .filter(association__id=association_id) \
                                   .filter(ends_at__year=int(year)) \
                                   .order_by('-ends_at')[0:1].get()
                if last_mandate is not None:
                    people = People.objects.filter(mandate__id=last_mandate.id).count()
                    #President and treasurer at least
                    if people >= 2:
                        achieved = True
            except Mandate.DoesNotExist:
                pass

        if self.type == 'accomplishment':
            accomplishment = Accomplishment.objects \
                .filter(requirement__id=self.id) \
                .filter(association__id=association_id) \
                .count()
            if accomplishment > 0:

templates/association/base_association.html
{% extends 'base.html' %}

{% block page_seo %}
    <title>{{ association.name }}{% if association.acronym %} ({{ association.acronym }}){% endif %}</title>
    <meta name="title" content="{{ association.name }}{% if association.acronym %} ({{ association.acronym }}){% endif %}"/>
{% endblock %}

{% block page_title %}
  {{ association.name }}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      <div class="list-group table-of-contents">
        <a class="list-group-item list-group-item-action{% if request.resolver_match.url_name == 'association-detail' %} active{% endif %}" href="{% url 'association-detail' association.id %}"><i class="fa fa-eye"></i> Vue générale</a>
        <a class="list-group-item list-group-item-action{% if request.resolver_match.url_name == 'association-requirement-list' %} active{% endif %}" href="{% url 'association-requirement-list' association.id %}"><i class="fa fa-check-square-o"></i> Situation administrative</a>
        <a class="list-group-item list-group-item-action{% if 'association-file' in request.resolver_match.url_name or request.resolver_match.url_name == 'association-resource-tree' %} active{% endif %}" href="{% url 'association-file-tree' association.id %}"><i class="fa fa-file"></i> Fichiers</a>
        <a class="list-group-item list-group-item-action{% if 'association-directory' in request.resolver_match.url_name %} active{% endif %}" href="{% url 'association-directory-detail' association.id %}"><i class="fa fa-book"></i> Bot'INSA</a>
        <a class="list-group-item list-group-item-action{% if 'association-mandate' in request.resolver_match.url_name %} active{% endif %}" href="{% url 'association-mandate-list' association.id %}"><i class="fa fa-users"></i> Mandats (bureaux)</a>
        <a class="list-group-item list-group-item-action{% if 'association-event' in request.resolver_match.url_name %} active{% endif %}" href="{% url 'association-event-list' association.id %}"><i class="fa fa-calendar-check-o"></i> Evénements</a>
        <a class="list-group-item list-group-item-action{% if 'association-article' in request.resolver_match.url_name %} active{% endif %}" href="{% url 'association-article-list' association.id %}"><i class="fa fa-pencil"></i> Articles</a>
      </div>
    </div>
    <div class="col-md-9">
      {% block content_association %}{% endblock %}
    </div>
  </div>
{% endblock %}

templates/association/delete.html
{% extends 'base.html' %}

{% block page_seo %}
    <title>Suppression d'une association</title>
    <meta name="title" content="Suppression d'une association"/>
{% endblock %}

{% block page_title %}
  Suppression d'une association
{% endblock %}

{% block page_sub_title %}
  {{ association.name }}
{% endblock %}

{% block quick_actions %}
  <a href="{% url 'association-list' %}" class="btn btn-secondary">Annuler</a>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <div class="alert alert-danger" role="alert">
        <strong>Attention !</strong> La suppression de l'association <i>{{ association.name }}</i> entraînera la <u>perte irréversible</u> des données y étant associées.<br>
        Voulez-vous <u>vraiment</u> poursuivre ?
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <p class="text-center">
          <input class="btn btn-danger" type="submit" value="Confirmer la suppression" />
        </p>
      </form>
    </div>
  </div>
{% endblock %}

templates/association/global_directory.html
{% extends 'base.html' %}

{% block page_seo %}
    <title>Annuaire des associations</title>
    <meta name="title" content="Annuaire des associations"/>
{% endblock %}

{% block page_title %}
    Annuaire des associations
{% endblock %}

{% block content %}
    <div class="row">
    <table id="prettyTable" class="table table-bordered table-responsive datatables" data-page-length="50">
        <thead>
        <tr>
            <th>Nom de l'association</th>
            <th>Nom du président</th>
            <th>Email de contact</th>
            <th>Numéro de téléphone</th>
            <th>Fin du mandat</th>
        </tr>
        </thead>
        <tbody>
        {% for association in object_list %}
            {% with mandate=association.mandates.last %}
                <tr>
                    {% if request.user.is_active and request.user.is_staff %}
                        {% if not association.acronym %}
                            <td><a href="{% url 'association-detail' association.id %}">{{ association.name }}</a></td>
                        {% else %}
                            <td><a href="{% url 'association-detail' association.id %}">{{ association.acronym }}</a> <small>({{ association.name }})</small></td>
                        {% endif %}
                    {% else %}
                        {% if not association.acronym %}
                            <td> {{ association.name }} </td>
                        {% else %}
                            <td> {{ association.acronym }} <small>({{ association.name }})</small></td>
                        {% endif %}
                    {% endif %}
                    {% with president=mandate.get_president.first %}
                        <td>{{ president.last_name|upper }} {{ president.first_name|title }}</td>
                        <td>
                            <a href="mailto:{{ association.directory_entries.last.contact_address }}">
                                {{ association.directory_entries.last.contact_address }}
                            </a>
                        </td>
                        <td>
                            {% if mandate.share_phone %}
                                {{ president.phone }}
                            {% else %}
                                Privé
                            {% endif %}
                        </td>
                    {% endwith %}
                    <td data_order="mandate.ends_at">{{ mandate.ends_at|date:'DATE_FORMAT' }}</td>
                </tr>
            {% endwith %}
        {% endfor %}

        </tbody>
    </table>
    </div>
{% endblock %}

templates/association/list.html
{% extends 'base.html' %}

{% block page_seo %}
    <title>Liste des associations</title>
    <meta name="title" content="Liste des associations"/>
{% endblock %}

{% block page_title %}
    Liste des associations
{% endblock %}

{% block quick_actions %}
    <a href="{% url 'association-new' %}" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter</a>
{% endblock %}

{% block content %}
    <div class="row">
        <table id="prettyTable" class="table table-bordered table-stripped datatables" data-order="[[ 2, &quot;desc&quot; ]]" data-page-length="100">
            <thead>
            <tr>
                <th>Acronyme - Nom</th>
                <th>Validée</th>
                <th>Active</th>
                <th data-orderable="false">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for association in object_list %}
                <tr>
                    {% if not association.acronym %}
                        <td><a href="{% url 'association-detail' association.id %}">{{ association.name }}</a></td>
                    {% else %}
                        <td><a href="{% url 'association-detail' association.id %}">{{ association.acronym }}</a> <small>({{ association.name }})</small></td>
                    {% endif %}
                    <td data-order="{{ association.is_validated }}">
                        {% if association.is_validated %}
                            <i class="fa fa-check"></i>
                        {% else %}
                            <i class="fa fa-times"></i>
                        {% endif %}
                    </td>
                    <td data-order="{{ association.is_active }}">
                        {% if association.is_active %}
                            <i class="fa fa-check"></i>
                        {% else %}
                            <i class="fa fa-times"></i>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'association-update' association.id %}" data-toggle="tooltip"
                           title="Modifier les informations"><i class="fa fa-pencil"></i></a>
                        <a href="{% url 'association-delete' association.id %}" data-toggle="tooltip"
                           title="Supprimer l'association"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/association/new.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block css_js_header %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
{% endblock %}

{% block page_seo %}
    <title>Ajouter une association</title>
    <meta name="title" content="Ajouter une association"/>
{% endblock %}

{% block page_title %}
  Ajouter une association
{% endblock %}

{% block quick_actions %}
<a href="{% url 'association-list' %}" class="btn btn-secondary"><i class="fa fa-times"></i> Annuler</a>
<button form="associationForm" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Enregistrer</button>
{% endblock %}

{% block content %}
  {% crispy form %}
{% endblock %}

{% block js %}
    <script type="application/javascript">
    <!--
        "use strict";

        const $roomDivSelector = $('#div_id_room');
        const $placeCheckSelector = $('#div_id_has_place input');

        if(!$placeCheckSelector.is(':checked')){
            $roomDivSelector.hide('fast');
        }

        $placeCheckSelector.on('change', function () {
            if($placeCheckSelector.is(':checked')){
                $roomDivSelector.show('slow');
            }else{
                $roomDivSelector.hide('fast');
            }
        });

        $roomDivSelector.find('select').first().select2({
            width: '100%',
            dropdownAutoWidth: true,
            quietMillis: 100,
            minimumResultsForSearch: 10,
            formatSelection: function(object, container) {
                text = object.text;
                if (object.element[0].parentElement.nodeName === 'OPTGROUP') {
                    text = object.element[0].parentElement.getAttribute('label') + ' - ' + text;
                }
                return text;
            },
            formatResult: function(result, container) {
                container.attr('title', result.title || result.element[0].title);
                return result.text;
            },
            sorter: function(data) {
                return data.sort(function(a, b) {
                    return (a.text < b.text) ? -1 : (a.text > b.text ? 1 : 0);
                });
            },
            language: {
                noResults: function(){
                    return "Aucun lieu correspond à (ou contient) ce nom !";
               }
            },
        }).bind('setValue', function(e, value) {
            $('#id_room').val(value).trigger('change');
        });

        $roomDivSelector.find('label').first().on('click', function() { $roomDivSelector.find('select').first().select2('open'); });
    //-->
    </script>
{% endblock %}

templates/association/update.html
{% extends 'association/base_association.html' %}

{% load crispy_forms_tags %}

{% block css_js_header %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
{% endblock %}

{% block page_sub_title %}
  Modifier les informations
{% endblock %}

{% block quick_actions %}
<a href="{% url 'association-detail' association.id %}" class="btn btn-secondary"><i class="fa fa-times"></i> Annuler</a>
<button form="associationForm" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Enregistrer</button>
{% endblock %}

{% block content_association %}
  {% crispy form %}
{% endblock %}

{% block js %}
    <script type="application/javascript">
    <!--
        "use strict";

        const $roomDivSelector = $('#div_id_room');
        const $placeCheckSelector = $('#div_id_has_place input');

        if(!$placeCheckSelector.is(':checked')){
            $roomDivSelector.hide('fast');
        }

        $placeCheckSelector.on('change', function () {
            if($placeCheckSelector.is(':checked')){
                $roomDivSelector.show('slow');
            }else{
                $roomDivSelector.hide('fast');
            }
        });

        $roomDivSelector.find('select').first().select2({
            width: '100%',
            dropdownAutoWidth: true,
            quietMillis: 100,
            minimumResultsForSearch: 10,
            formatSelection: function(object, container) {
                text = object.text;
                if (object.element[0].parentElement.nodeName === 'OPTGROUP') {
                    text = object.element[0].parentElement.getAttribute('label') + ' - ' + text;
                }
                return text;
            },
            formatResult: function(result, container) {
                container.attr('title', result.title || result.element[0].title);
                return result.text;
            },
            sorter: function(data) {
                return data.sort(function(a, b) {
                    return (a.text < b.text) ? -1 : (a.text > b.text ? 1 : 0);
                });
            },
            language: {
                noResults: function(){
                    return "Aucun lieu correspond à (ou contient) ce nom !";
               }
            },
        }).bind('setValue', function(e, value) {
            $('#id_room').val(value).trigger('change');
        });

        $roomDivSelector.find('label').first().on('click', function() { $roomDivSelector.find('select').first().select2('open'); });
    //-->
    </script>
{% endblock %}