portailva/directory/api_v1/urls.py
from django.conf.urls import url

from .views import DirectoryAPIView, PrivateDirectoryAPIView, PublicDirectoryByIdAPIView

urlpatterns = [
    url('^private/$', PrivateDirectoryAPIView.as_view(), name='api-v1-directory-private'),
    url('^(?P<association_pk>\d+)/$', PublicDirectoryByIdAPIView.as_view(), name='api-v1-directory-detail'),
    url('^$', DirectoryAPIView.as_view(), name='api-v1-directory-index'),
]

portailva/directory/urls.py
from django.conf.urls import url

from .views import AssociationDirectoryEntryDetailView, AssociationDirectoryEntryUpdateView, \
    AssociationDirectoryEntryOpeningHourCreateView, AssociationDirectoryEntryOpeningHourUpdateView, \
    AssociationDirectoryEntryOpeningHourDeleteView, AssociationDirectoryEntryPublishView, \
    AssociationDirectoryEntryDeleteView, AssociationDirectoryPublicView, AssociationPrintView, \
    AssociationDirectoryTexView

urlpatterns = [
    url('^association/(?P<association_pk>\d+)/directory/$', AssociationDirectoryEntryDetailView.as_view(),
        name='association-directory-detail'),
    url('^association/(?P<association_pk>\d+)/directory/edit/$', AssociationDirectoryEntryUpdateView.as_view(),
        name='association-directory-update'),
    url('^association/(?P<association_pk>\d+)/directory/opening_hour/new/$', AssociationDirectoryEntryOpeningHourCreateView
        .as_view(), name='association-directory-opening-hour-new'),
    url('^association/(?P<association_pk>\d+)/directory/opening_hour/(?P<pk>\d+)/update/$',
        AssociationDirectoryEntryOpeningHourUpdateView.as_view(), name='association-directory-opening-hour-update'),
    url('^association/(?P<association_pk>\d+)/directory/opening_hour/(?P<pk>\d+)/delete/$',
        AssociationDirectoryEntryOpeningHourDeleteView.as_view(), name='association-directory-opening-hour-delete'),

    # Admin stuff
    url('^association/(?P<association_pk>\d+)/directory/publish/$', AssociationDirectoryEntryPublishView.as_view(),
        name='association-directory-publish'),
    url('^association/(?P<association_pk>\d+)/directory/delete/$', AssociationDirectoryEntryDeleteView.as_view(),
        name='association-directory-delete'),

    url('^association/botinsa/$', AssociationDirectoryPublicView.as_view(), name='association-directory-public'),
    url('^association/botinsa-latex/$', AssociationDirectoryTexView.as_view(), name='association-directory-latex'),
    url('^association/(?P<pk>\d+)/print/$', AssociationPrintView.as_view(), name='association-print'),
]

portailva/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from portailva.pages.views import HomeView, DashBoardView, Handler400, Handler503, Handler404, Handler403, Handler401, \
    Handler502, MentionView, SitemapView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/$', DashBoardView.as_view(), name='admin-dashboard'),

    url(r'', include('portailva.association.urls')),
    url(r'^member/', include('portailva.member.urls')),
    url(r'', include('portailva.directory.urls')),
    url(r'', include('portailva.file.urls')),
    url(r'', include('portailva.utils.urls')),
    url(r'', include('portailva.event.urls')),
    url(r'', include('portailva.newsletter.urls')),
    url(r'export/', include('portailva.export.urls')),

    # REST API
    url(r'^api/', include('portailva.api_urls')),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^mention/$', MentionView.as_view(), name='mention'),
    url('^sitemap.xml$', SitemapView.as_view(), name='public-article-sitemap'),
    url(r'^$', HomeView.as_view(), name='homepage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = Handler400.as_view() # Bad Request
handler401 = Handler401.as_view() # Unauthorized
handler403 = Handler403.as_view() # Forbidden
handler404 = Handler404.as_view() # Not Found
handler500 = 'portailva.pages.views.handler500' # Internal Server Error
handler502 = Handler502.as_view() # Bad Gateway
handler503 = Handler503.as_view() # Service Unavailable

portailva/directory/models.py
import os

from itertools import groupby

from django.db import models

from portailva.association.models import Association
from portailva.utils.models import Place


class DirectoryEntryManager(models.Manager):
    def get_last_for_association_id(self, association_id):
        return self.get_queryset()\
            .filter(association_id=association_id)\
            .order_by('-id')[:1][0]

    def get_last_active(self):
        return [list(g)[0] for k, g in groupby(DirectoryEntry.objects.all().filter(is_online=True)
                                               .order_by('association__name', '-created_at'), lambda x: x.association_id)]


class DirectoryEntry(models.Model):
    """
    A DirectoryEntry contains useful information about an Association.
    It contains address and some contact information.
    """
    description = models.TextField("Description de l'association", max_length=900, help_text='{}/900 caractère{}')
    contact_address = models.EmailField("Adresse de contact")
    phone = models.CharField("Téléphone", max_length=10, blank=True)

    website_url = models.URLField("URL site web", null=True, blank=True)
    facebook_url = models.URLField("URL page Facebook", null=True, blank=True)
    twitter_url = models.URLField("URL fil Twitter", null=True, blank=True)
    instagram_url = models.URLField("URL fil Instagram", null=True, blank=True)
    discord_url = models.URLField("URL serveur Discord", null=True, blank=True)

    association = models.ForeignKey(Association, verbose_name="Association", related_name="directory_entries",
                                    on_delete=models.CASCADE)
    place = models.ForeignKey(Place, verbose_name="Lieu", related_name="associations", null=True, blank=True,
                              on_delete=models.SET_NULL)

    is_online = models.BooleanField("Est publié", default=False)

    created_at = models.DateTimeField("Date d'ajout", auto_now_add=True)
    updated_at = models.DateTimeField("Dernière mise à jour", auto_now=True)

    objects = DirectoryEntryManager()

    class Meta(object):
        default_permissions = ('add', 'change', 'delete', 'admin',)

    def __str__(self):
        return "[" + self.association.name + "] Version du " + str(self.created_at)

    @property
    def public_phone(self):
        if (self.phone == ''
                or self.phone.startswith('06') or self.phone.startswith('+336') or self.phone.startswith('336')
                or self.phone.startswith('07') or self.phone.startswith('+337') or self.phone.startswith('337')):
            return {
                'phone': os.getenv('BDE_PHONE'),
                'source': "Standard BdE"
            }
        else:
            return {
                'phone': self.phone,
            }

    @property
    def api_phone(self):
        if (self.phone.startswith('06') or self.phone.startswith('+336') or self.phone.startswith('336')
                or self.phone.startswith('07') or self.phone.startswith('+337') or self.phone.startswith('337')):
            return ''
        return self.phone


class OpeningHour(models.Model):
    """
    An OpeningHour is a time range when association welcomes visitors.
    """
    DAYS_OF_WEEK = (
        (1, 'Lundi'),
        (2, 'Mardi'),
        (3, 'Mercredi'),
        (4, 'Jeudi'),
        (5, 'Vendredi'),
        (6, 'Samedi'),
        (7, 'Dimanche'),
    )
    day = models.IntegerField("Jour d'ouverture", choices=DAYS_OF_WEEK)
    begins_at = models.TimeField("Heure d'ouverture")
    ends_at = models.TimeField("Heure de fermeture")

    directory_entry = models.ForeignKey(DirectoryEntry, verbose_name="Version du Bot'INSA",
                                        related_name="opening_hours", on_delete=models.CASCADE)

    class Meta(object):
        default_permissions = ('add', 'change', 'delete', 'admin',)
        ordering = ('day', 'begins_at', )

    def __str__(self):
        return "[" + self.directory_entry.association.name + "] " + self.get_day_display() + " de " +\
               str(self.begins_at) + " à " + str(self.ends_at) + " - Version du " +\
               str(self.directory_entry.created_at)

portailva/directory/forms.py
from bootstrap3_datetime.widgets import DateTimePicker
from crispy_forms.helper import FormHelper
from django import forms
from django.conf import settings

from .models import DirectoryEntry, OpeningHour


class DirectoryEntryForm(forms.ModelForm):
    class Meta(object):
        model = DirectoryEntry
        fields = ['description', 'contact_address', 'phone', 'website_url', 'facebook_url', 'twitter_url', 'instagram_url', 'discord_url', 'place']

    def __init__(self, *args, **kwargs):
        super(DirectoryEntryForm, self).__init__(*args, **kwargs)

        description_length = len(self.initial.get('description', ''))
        template_help_text = self.fields['description'].help_text

        self.fields['description'].help_text = template_help_text.format(description_length,
                                                                         's' if (description_length > 0) else '')
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_error_title = 'Veuillez corriger les erreurs suivantes :'
        self.helper.form_id = 'directoryEntryForm'


class OpeningHourForm(forms.ModelForm):
    begins_at = forms.TimeField(
        label="Heure d'ouverture",
        # widget=DateTimePicker(options=settings.PICKER_TIME_OPTIONS),
        help_text="Format : HH:MM"
    )

    ends_at = forms.TimeField(
        label="Heure de fermeture",
        # widget=DateTimePicker(options=settings.PICKER_TIME_OPTIONS),
        help_text="Format : HH:MM"
    )

    class Meta(object):
        model = OpeningHour
        fields = ['day', 'begins_at', 'ends_at']

    def __init__(self, *args, **kwargs):
        super(OpeningHourForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_error_title = 'Veuillez corriger les erreurs suivantes :'
        self.helper.form_id = 'openingHourForm'

    def clean(self):
        super(OpeningHourForm, self).clean()
        begins_at = self.cleaned_data.get('begins_at', None)
        ends_at = self.cleaned_data.get('ends_at', None)
        if begins_at is None or ends_at is None:
            raise forms.ValidationError("Veuillez renseigner les horaires d'ouverture et de fermeture.",
                                        code='invalidTime')
        if begins_at > ends_at:
            raise forms.ValidationError("Les horaires renseignés sont incohérents, "
                                        "vérifiez que vous ouvrez bien avant de fermer sur ce créneau.",
                                        code='invalidBegin')
        if begins_at == ends_at:
            raise forms.ValidationError("Les horaires renseignés sont identiques, "
                                        "veuillez changer l'horaire d'ouverture ou de fermeture.",
                                        code='invalidEqual')
        return self.cleaned_data

portailva/directory/api_v1/views.py
from django.http import Http404
from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.permissions import AllowAny, IsAdminUser

from portailva.directory.models import DirectoryEntry
from .serializers import DirectoryEntrySerializer, PrivateDirectoryEntrySerializer, DetailDirectoryEntrySerializer


class DirectoryAPIView(ListAPIView):
    serializer_class = DirectoryEntrySerializer
    permission_classes = (AllowAny,)

    def get_queryset(self):
        return DirectoryEntry.objects.get_last_active()


class PublicDirectoryByIdAPIView(RetrieveAPIView):
    permission_classes = (AllowAny,)
    serializer_class = DetailDirectoryEntrySerializer

    def get_object(self):
        try:
            return DirectoryEntry.objects.get_last_for_association_id(self.kwargs.get('association_pk'))
        except IndexError:
            raise Http404


class PrivateDirectoryAPIView(DirectoryAPIView):
    permission_classes = (IsAdminUser,)
    serializer_class = PrivateDirectoryEntrySerializer

templates/directory/asso_modals.html
<!-- Basic modal -->
<div class="modal fade" id="assoDetails" tabindex="-1" role="dialog" aria-labelledby="assoDetailsLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modal-association-title" style="height: 100%; width: 100%;"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="info-tab" data-toggle="tab"
                           href="#info" role="tab"
                           aria-controls="info" aria-expanded="true">
                            Infos générales
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="hours-tab" data-toggle="tab"
                           href="#hours" role="tab"
                           aria-controls="hours">
                            Horaires
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="events-tab" data-toggle="tab"
                           href="#events" role="tab"
                           aria-controls="events">
                            Évènements
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="info" role="tabpanel"
                         aria-labelledby="info-tab">

                        <div class="row">
                            <div class="col-12" id="modal-association-description"></div>
                        </div>

                        <div class="row">
                            <div class="col-md-6" id="modal-association-place"></div>
                            <div class="col-md-6" id="modal-association-website"></div>
                        </div>

                        <div class="row">
                            <div class="col-md-6" id="modal-association-contact"></div>
                            <div class="col-md-6" id="modal-association-network"></div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="hours" role="tabpanel"
                         aria-labelledby="hours-tab" data-children=".item">
                    </div>
                    <div class="tab-pane fade" id="events" role="tabpanel"
                         aria-labelledby="events-tab" data-children=".item">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="btn-group">
                    <a href="{% url 'association-print' 0 %}" class="btn btn-light">
                        Version imprimable
                    </a>
                    {% if user.is_superuser %}
                        <a href="{% url 'association-detail' 0 %}" class="btn btn-light">
                            Admin
                        </a>
                    {% endif %}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/directory/delete.html
{% extends 'association/base_association.html' %}

{% block page_sub_title %}
  Supprimer une page du Bot'INSA
{% endblock %}

{% block quick_actions %}
  <a href="{% url 'association-directory-detail' association.id %}" class="btn btn-secondary"><i class="fa fa-times"></i> Annuler</a>
{% endblock %}

{% block content_association %}
  <div class="row">
    <div class="col-12">
      <div class="alert alert-danger" role="alert">
        <strong>Attention !</strong> Vous vous apprêtez à supprimer cette association du Bot'INSA. Cette action est <u>irréversible</u>.<br>
        Voulez-vous <u>vraiment</u> poursuivre ?
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <p class="text-center">
          <input class="btn btn-danger" type="submit" value="Confirmer la suppression" />
        </p>
      </form>
    </div>
  </div>
{% endblock %}

templates/directory/detail.html
{% extends 'association/base_association.html' %}

{% load l10n %}

{% block page_sub_title %}
    Bot'INSA
{% endblock %}

{% block quick_actions %}
    {% if perms.association.admin_directoryentry %}
        {% if object != None %}
            <a href="{% url 'association-print' association.id %}" class="btn btn-secondary"><i class="fa fa-print"></i> Voir la version publiée</a>
            <a href="{% url 'association-directory-delete' association.id %}" class="btn btn-danger"><i
                    class="fa fa-trash"></i> Supprimer</a>
            {% if not object.is_online %}
                <a href="{% url 'association-directory-publish' association.id %}" class="btn btn-success"><i
                        class="fa fa-check"></i> Publier</a>
            {% endif %}
        {% endif %}
    {% endif %}
    <a href="{% url 'association-directory-update' association.id %}" class="btn btn-primary"><i
            class="fa fa-pencil"></i> Mettre à jour</a>
{% endblock %}

{% block content_association %}
    {% if not object %}
        <div class="alert alert-warning" role="alert">
            Vous n'avez jamais rempli de page pour le Bot'INSA.
        </div>
    {% else %}
        {% if not object.is_online %}
            <div class="alert alert-warning" role="alert">
                Cette version est en cours de validation par le responsable VA. Elle n'est donc pas encore publiée.
            </div>
        {% endif %}

        <div class="row mb-3">
            <div class="col-12">
                <strong>Description</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {{ object.description|linebreaksbr }}
                        <br/>
                        <small class="card-text text-muted {% if object.description|length >= 900 %}has-error{% endif %}">
                            {{ object.description|length }}/900 caractères
                        </small>
                    </div>
                </div>

            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <strong>Adresse de contact</strong>
                <div class="card bg-light">
                    <div class="card-body"><a
                            href="mailto:{{ object.contact_address }}">{{ object.contact_address }}</a></div>
                </div>
            </div>
            <div class="col-md-6">
                <strong>Numéro de téléphone</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {% if object.phone %}
                            <a href="tel:{{ object.phone }}">{{ object.phone }}</a>
                        {% else %}
                            <i>Non défini</i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <strong>Horaires de permanence</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        <table class="table">
                            <tbody>
                            {% for opening_hour in object.opening_hours.all %}
                                <tr>
                                    <td>{{ days|get_tuple:opening_hour.day }}</td>
                                    <td>de {{ opening_hour.begins_at|time:"H:i" }}</td>
                                    <td>à {{ opening_hour.ends_at|time:"H:i" }}</td>
                                    <td>
                                        <a href="{% url 'association-directory-opening-hour-update' association.id opening_hour.id %}"
                                           data-toggle="tooltip" title="Modifier"><i class="fa fa-pencil"></i></a>
                                        <a href="{% url 'association-directory-opening-hour-delete' association.id opening_hour.id %}"
                                           data-toggle="tooltip" title="Supprimer"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="4"><a
                                        href="{% url 'association-directory-opening-hour-new' association.id %}">Ajouter
                                    un horaire</a></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <strong>Lieu</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {% if object.place_id %}
                            <a href="http://www.openstreetmap.org/?mlat={{ object.place.lat|unlocalize }}&mlon={{ object.place.long|unlocalize }}&zoom=18">
                                {{ object.place.name }}
                            </a>
                        {% else %}
                            <i>Non défini</i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <strong>URL site web</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {% if object.website_url %}
                            <a href="{{ object.website_url }}">{{ object.website_url }}</a>
                        {% else %}
                            <i>Non défini</i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <strong>URL page Facebook</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {% if object.facebook_url %}
                            <a href="{{ object.facebook_url }}">{{ object.facebook_url }}</a>
                        {% else %}
                            <i>Non défini</i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <strong>URL fil Twitter</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {% if object.twitter_url %}
                            <a href="{{ object.twitter_url }}">{{ object.twitter_url }}</a>
                        {% else %}
                            <i>Non défini</i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <strong>URL fil Instagram</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {% if object.instagram_url %}
                            <a href="{{ object.instagram_url }}">{{ object.instagram_url }}</a>
                        {% else %}
                            <i>Non défini</i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <strong>URL serveur Discord</strong>
                <div class="card bg-light">
                    <div class="card-body">
                        {% if object.discord_url %}
                            <a href="{{ object.discord_url }}">{{ object.discord_url }}</a>
                        {% else %}
                            <i>Non défini</i>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <p>
            <small><i>Dernière modification : {{ object.updated_at|date:'DATETIME_FORMAT' }}</i></small>
        </p>
    {% endif %}
{% endblock %}

templates/directory/publish.html
{% extends 'association/base_association.html' %}

{% block page_sub_title %}
  Publier une page du Bot'INSA
{% endblock %}

{% block quick_actions %}
  <a href="{% url 'association-directory-detail' association.id %}" class="btn btn-secondary"><i class="fa fa-times"></i> Annuler</a>
{% endblock %}

{% block content_association %}
  <div class="row">
    <div class="col-12">
      <div class="alert alert-success" role="alert">
        Êtes-vous sûr de vouloir publier la dernière version du Bot'INSA pour cette association ?
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <p class="text-center">
          <button class="btn btn-success" type="submit">Confirmer la publication</button>
        </p>
      </form>
    </div>
  </div>
{% endblock %}

templates/directory/update.html
{% extends 'association/base_association.html' %}

{% load crispy_forms_tags %}

{% block css_js_header %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
{% endblock %}

{% block page_sub_title %}
    Modifier le Bot'INSA
{% endblock %}

{% block quick_actions %}
    <a href="{% url 'association-directory-detail' association.id %}" class="btn btn-secondary"><i class="fa fa-times"></i> Annuler</a>
    <button form="directoryEntryForm" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Enregistrer</button>
{% endblock %}

{% block content_association %}
    {% crispy form %}

    <script type="text/javascript">
    //<![CDATA[
        "use strict";
        let descriptionArea=$('#id_description');
        descriptionArea.on('input', function() {
            const charNumber = $(this).val().trim().replace(/\n/g,"\r\n").length;

            let counter = $('#hint_id_description');
            counter.html(charNumber + '/900 caractère' + (charNumber > 1 ? 's' : ''));
            if (charNumber > 900) {
                counter.addClass('has-error');
            }else{
                counter.removeClass('has-error');
            }
        });

        descriptionArea.trigger("input");
    //]]>
    </script>
{% endblock %}


{% block js %}
    <script type="application/javascript">
    <!--
        "use strict";
        $('#id_place').select2({
            width: '100%',
            dropdownAutoWidth: true,
            quietMillis: 100,
            minimumResultsForSearch: 10,
            formatSelection: function(object, container) {
                text = object.text;
                if (object.element[0].parentElement.nodeName === 'OPTGROUP') {
                    text = object.element[0].parentElement.getAttribute('label') + ' - ' + text;
                }
                return text;
            },
            formatResult: function(result, container) {
                container.attr('title', result.title || result.element[0].title);
                return result.text;
            },
            sorter: function(data) {
                return data.sort(function(a, b) {
                    return (a.text < b.text) ? -1 : (a.text > b.text ? 1 : 0);
                });
            },
            language: {
                noResults: function(){
                    return "Aucun lieu correspond à (ou contient) ce nom !";
               }
            },
        }).bind('setValue', function(e, value) {
            $('#id_place').val(value).trigger('change');
        });
        $('label[for=id_place]').on('click', function() { $('#id_place').select2('open'); });
    //-->
    </script>
{% endblock %}